---
- hosts: localhost
  vars_files:
     - vars/machine_vars.yml
     - vars/pkgs.yml

  tasks:
    - block:
        - name: check packages
          command: "pacman -Qi {{ ( pkgs + machine_pkgs ) | join(' ')  }}"
          no_log: true
          changed_when: false
      rescue:
        - name: install packages      
          shell: yaourt -S {{ item }} --needed --noconfirm
          register: yaourt_out
          changed_when: "yaourt_out.stdout is search('resolving')"
          with_items: "{{pkgs + machine_pkgs}}"  

    - name: configure i3
      template:
          src: templates/i3/config
          dest: ~/.i3/config
      notify: restart i3

    - name: configure polybar 
      copy:
          src: templates/polybar
          dest: ~/.config
      notify: restart i3
     
    - name: configure autorandr 
      copy:
          src: templates/postswitch
          dest: ~/.config/autorandr
          mode: '0751'
     
    - name: configure gitconfig 
      template:
          src: templates/gitconfig
          dest: ~/.gitconfig

    - name: configure gtk2 
      copy:
          src: templates/gtkrc-2.0 
          dest: ~/.gtkrc-2.0 

    - name: configure gtk3 
      copy:
          src: templates/gtk-3.0 
          dest: ~/.config 

    - name: configure xmodmap 
      copy:
          src: templates/Xmodmap
          dest: ~/.Xmodmap
     
    - name: configure vim 
      copy:
          src: templates/vimrc
          dest: ~/.vimrc

    - name: configure vim for root 
      copy:
          src: templates/vimrc
          dest: /root/.vimrc
      become: yes

    - name: configure ranger
      copy:
          src: templates/ranger
          dest: ~/.config

    - name: configure rofi 
      copy:
          src: templates/rofi_config
          dest: ~/.config/rofi/config

    - name: configure geoclue 
      copy:
          src: templates/geoclue.conf
          dest: /etc/geoclue/geoclue.conf
      become: yes

    - name: configure profile 
      template:
          src: templates/profile
          dest: ~/.profile

    - name: start geoclue 
      systemd: state=started enabled=yes name=geoclue
      become: yes 

    - name: start clight 
      systemd: state=started enabled=yes name=clightd
      become: yes 

    - name: configure yaourt 
      copy:
          src: templates/yaourtrc
          dest: ~/.yaourtrc

    - name: configure xresources 
      copy:
          src: templates/Xresources
          dest: ~/.Xresources
      notify: load xrdb

    - name: configure inputrc 
      copy:
          src: templates/inputrc
          dest: ~/.inputrc
      notify: re-source bashrc

    - name: configure bashrc 
      copy:
          src: templates/bashrc
          dest: ~/.bashrc
      notify: re-source bashrc

    - name: configure bashrc for root 
      copy:
          src: templates/bashrc
          dest: /root/.bashrc
      become: yes

    - name: configure pacman
      copy:
          src: templates/pacman.conf
          dest: /etc/pacman.conf
      become: yes

    - name: configure jupyter 
      copy:
          src: templates/jupyter/
          dest: ~/.jupyter

    - block:
        - name: create pacman hooks dir
          file:
            path: /etc/pacman.d/hooks
            state: directory
            owner: root
            group: root
        - name: copy pacman hooks config
          copy:
            src: templates/pacman_cleanup.hook
            dest: /etc/pacman.d/hooks/cleanup.hook
      become: yes

    - block:
        - name: check if YNAB 4 is installed
          stat:
            path: ~/scripts/run_ynab4.sh
          register: ynab_stat
        - name: copy run script to ~/scripts
          copy:
            src: scripts/run_ynab4.sh
            dest: ~/scripts/run_ynab4.sh
            mode: u+rwx,g-wx,o-wx
          when: not ynab_stat.stat.exists
        - name: create symlink
          file:
            src: ~/scripts/run_ynab4.sh
            dest:  ~/scripts/ynab
            state: link
            mode: u+rwx,g-wx,o-wx
          when: not ynab_stat.stat.exists
    
  handlers:
    - name: restart i3
      command: i3-msg restart
      failed_when: false
   
    - name: re-source bashrc
      shell: source ~/.bashrc

    - name: load xrdb
      command: xrdb -load ~/.Xresources

