---
- hosts: localhost
  vars_files:
     - vars/machine_vars.yml
     - vars/pkgs.yml

  tasks:
    - block:
        - name: check packages
          command: "pacman -Qi {{ ( pkgs + machine_pkgs ) | join(' ')  }}"
          no_log: true
          changed_when: false
      rescue:
        - name: install packages      
          shell: yaourt -S {{ item }} --needed --noconfirm
          register: yaourt_out
          changed_when: "yaourt_out.stdout is search('resolving')"
          with_items: "{{pkgs + machine_pkgs}}"  

    - name: configure i3
      template:
          src: templates/i3/config
          dest: ~/.i3/config
      notify: restart i3

    - name: configure i3status
      copy:
          src: templates/i3/i3status.conf
          dest: ~/.i3/i3status.conf
      notify: restart i3
     
    - name: configure gitconfig 
      template:
          src: templates/gitconfig
          dest: ~/.gitconfig

    - name: configure compton
      copy:
          src: templates/compton.conf
          dest: ~/.config/compton.conf

    - name: configure rofi 
      copy:
          src: templates/rofi_config
          dest: ~/.config/rofi/config

    - name: configure geoclue 
      copy:
          src: templates/geoclue.conf
          dest: /etc/geoclue/geoclue.conf
      become: yes

    - name: configure clight 
      copy:
          src: templates/clight.conf
          dest: ~/.config/clight.conf 

    - name: configure profile 
      copy:
          src: templates/profile
          dest: ~/.profile

    - name: start geoclue 
      systemd: state=started enabled=yes name=geoclue
      become: yes 

    - name: start clight 
      systemd: state=started enabled=yes name=clightd
      become: yes 

    - name: configure yaourt 
      copy:
          src: templates/yaourtrc
          dest: ~/.yaourtrc

    - name: configure xresources 
      copy:
          src: templates/Xresources
          dest: ~/.Xresources
      notify: load xrdb

    - name: configure inputrc 
      copy:
          src: templates/inputrc
          dest: ~/.inputrc
      notify: re-source bashrc

    - name: configure bashrc 
      copy:
          src: templates/bashrc
          dest: ~/.bashrc
      notify: re-source bashrc

    - name: configure jupyter 
      copy:
          src: templates/jupyter/
          dest: ~/.jupyter

    - name: install pacman cleanup hook
      block:
        - file:
            path: /etc/pacman.d/hooks
            state: directory
            owner: root
            group: root
        - template:
            src: templates/pacman_cleanup.hook
            dest: /etc/pacman.d/hooks/cleanup.hook
      become: yes
    
  handlers:
    - name: restart i3
      command: i3-msg restart
      failed_when: false
   
    - name: re-source bashrc
      shell: source ~/.bashrc

    - name: load xrdb
      command: xrdb -load ~/.Xresources

