call plug#begin('~/.vim/plugged')

" A sensible set of defaults for vim
Plug 'tpope/vim-sensible'

" A tree explorer plugin for vim
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }

" Colorscheme based on pywal
Plug 'dylanaraps/wal.vim'

call plug#end()

colorscheme wal

" Toggle NERDTree
map <C-n> :NERDTreeToggle<CR>

" Copy with ctrl+c and paste with ctrl+p
vnoremap <C-c> "*y :let @+=@*<CR>
map <C-p> "+P

" Relative numbers to make movements easier
set number relativenumber

" Autocompletion
set wildmode=longest,list,full

" Splits open at the bottom and right
set splitbelow splitright

