call plug#begin('~/.vim/plugged')

" A sensible set of defaults for vim
Plug 'tpope/vim-sensible'

" A tree explorer plugin for vim
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }

" To train vim best practices
Plug 'takac/vim-hardtime'

" Vue support
Plug  'leafOfTree/vim-vue-plugin', { 'for': 'vue' }

" For nice colors
Plug 'morhetz/gruvbox'

" Surround text easily
Plug 'tpope/vim-surround'

" Allows repeating plugin comands
Plug 'tpope/vim-repeat'

call plug#end()

colorscheme gruvbox
set background=dark

" Toggle NERDTree
map <C-n> :NERDTreeToggle<CR>

" Copy with ctrl+c and paste with ctrl+p
vnoremap <C-c> "*y :let @+=@*<CR>
map <C-p> "+P

" Relative numbers to make movements easier
set number relativenumber

" Autocompletion
set wildmode=longest,list,full

" Splits open at the bottom and right
set splitbelow splitright

let g:hardtime_default_on = 1
let g:list_of_disabled_keys = ["<UP>", "<DOWN>", "<LEFT>", "<RIGHT>"]
let g:vim_vue_plugin_load_full_syntax = 1
