---
- hosts: localhost
  vars:
    pkgs:
    # Dev
      - git
      - npm
      - nvm
      - yarn
      - mongodb
      - mongodb-tools
      - mariadb
      - visual-studio-code-bin
      - postman-bin
      - python-conda-build
      - pycharm-community-edition
    # Utilities
      - numlockx       # auto-activate numlock on boot
      - chromium 
      - redshift       # Eye protection
      - rofi
      - gvim
      - keepass
      - timeshift      # System Backups
      - dropbox
      - dynalist-desktop
      - ghetto-skype 
      - tmate
      - xclip
      - zip
      - wine
      - evince
      - gthumb
    # Drivers:
      - libva-intel-driver  # For intel graphics

    autostart:
      - chromium
      - redshift-gtk
      - dropbox
      - numlockx on
      - nitrogen --restore; sleep 1; compton -b
      - nm-applet
      - volumeicon
      - xfce4-power-manager
      - ~/.screenlayout/default.sh

  tasks:
    - block:
        - name: Check Packages
          command: "pacman -Qi {{ pkgs | join(' ')  }}"
          no_log: true
          changed_when: false
      rescue:
        - name: Install Packages      
          shell: yaourt -S {{ item }} --needed --noconfirm
          register: yaourt_out
          changed_when: "yaourt_out.stdout is search('resolving')"
          with_items: "{{ pkgs }}"  

    - name: Start mongodb
      systemd: state=started enabled=yes name=mongodb
      become: yes 

      #- name: Make sure mysql is started
      #systemd: state=started enabled=yes name=mysqld
      #become: yes

    - name: Activate conda in bashrc
      lineinfile:
          path: /home/gbottari/.bashrc
          line: ". /etc/profile.d/conda.sh"

    - name: Install i3 config
      template:
          src: templates/i3/config
          dest: ~/.i3/config
      notify: Restart i3

  handlers:
    - name: Restart i3
      command: i3-msg restart
      failed_when: false

