---
- hosts: localhost
  vars:
    pkgs:
      # System
      - numlockx       # auto-activate numlock on boot
      - firefox
      # Dev
      - git
      - npm
      - nvm
      - yarn
      - mongodb
      - mongodb-tools
      - mariadb
      - visual-studio-code-bin
      - postman-bin
      - python-conda-build
      # Utilities
      - geoclue2       # For redshift
      - redshift       # Eye protection
      - rofi
      - gvim
      - keepass
      - timeshift      # System Backups
      - dropbox
      - dynalist-desktop
      - ghetto-skype 
      # Windows
      - wine
      # Drivers
      - libva-intel-driver  # For intel graphics

    autostart:
      - compton -b
      - ~/.screenlayout/default.sh
      - nitrogen --restore &
      - numlockx on
      - nm-applet
      - volumeicon
      - xfce4-power-manager
      - firefox
      - redshift-gtk
      - dropbox

  tasks:
    - name: Install Packages      
      shell: yaourt -S {{ item }} --needed --noconfirm
      register: yaourt_out
      changed_when: "yaourt_out.stdout is search('resolving')"
      with_items: "{{ pkgs }}"  

    - name: Start mongodb
      systemd: state=started enabled=yes name=mongodb
      become: yes 

    - name: Start geoclue 
      systemd: state=started enabled=yes name=geoclue
      become: yes 

      #- name: Make sure mysql is started
      #systemd: state=started enabled=yes name=mysqld
      #become: yes

    - name: Activate conda in bashrc
      lineinfile:
          path: /home/gbottari/.bashrc
          line: ". /etc/profile.d/conda.sh"

    - name: Install i3 config
      template:
          src: templates/i3/config
          dest: ~/.i3/config
          
